[package]
name = "atomicwrites"
version = "0.0.14"

authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"
keywords = ["filesystem", "posix"]
readme = "README.md"

description = "Atomic file-writes."
documentation = "https://rust-atomicwrites.unterwaditzer.net/"
homepage = "https://rust-atomicwrites.unterwaditzer.net/"
repository = "https://github.com/untitaker/rust-atomicwrites"

[dependencies]
tempdir = "*"

[target.'cfg(unix)'.dependencies]
nix = "0.6.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
