[package]
name = "atomicwrites"
version = "0.0.6"

authors = ["Markus Unterwaditzer <markus@unterwaditzer.net>"]
license = "MIT"
keywords = ["filesystem", "posix"]
readme = "README.md"

description = "Atomic file-writes to POSIX filesystems."
documentation = "http://rust-atomicwrites.unterwaditzer.net/"
homepage = "http://rust-atomicwrites.unterwaditzer.net/"
repository = "https://github.com/untitaker/rust-atomicwrites"

[dependencies]
tempdir = "0.3"
